### ISSUE TITLE
Can't build with easy_install on windows

### ISSUE THREAD

**Issue by fgregg** [datamade/affinegap#2]
https://ci.appveyor.com/project/fgregg/dedupe/build/1.0.185

Always getting this same error:

```
Downloading https://pypi.python.org/packages/source/a/affinegap/affinegap-1.5.tar.gz#md5=f674711461037be8b6c868ba5132354b
Processing affinegap-1.5.tar.gz
Writing c:\users\appveyor\appdata\local\temp\1\easy_install-80tzbj\affinegap-1.5\setup.cfg
Running affinegap-1.5\setup.py -q bdist_egg --dist-dir c:\users\appveyor\appdata\local\temp\1\easy_install-80tzbj\affinegap-1.5\egg-dist-tmp-xosury
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    """
  File "C:\Python27_32\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Python27_32\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27_32\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27_32\lib\site-packages\setuptools\command\develop.py", line 32, in run
    self.install_for_development()
  File "C:\Python27_32\lib\site-packages\setuptools\command\develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 718, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Python27_32\lib\site-packages\pkg_resources\__init__.py", line 836, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\Python27_32\lib\site-packages\pkg_resources\__init__.py", line 1081, in best_match
    return self.obtain(req, installer)
  File "C:\Python27_32\lib\site-packages\pkg_resources\__init__.py", line 1093, in obtain
    return installer(requirement)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 638, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 668, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 851, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Python27_32\lib\site-packages\setuptools\command\easy_install.py", line 1065, in run_setup
    run_setup(setup_script, args)
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 240, in run_setup
    raise
  File "C:\Python27_32\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 193, in setup_context
    yield
  File "C:\Python27_32\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 152, in save_modules
    yield saved
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 126, in __exit__
    self._saved = UnpickleableException.dump(type, exc)
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "C:\Python27_32\lib\site-packages\setuptools\sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
MemoryError
Command exited with code 1
```

**Comment by fgregg** [comment]
building with pip
